---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: culler-sa
  namespace: culldemo01

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-culler-role
  namespace: culldemo01
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-culler-binding
  namespace: culldemo01
subjects:
- kind: ServiceAccount
  name: culler-sa
  namespace: culldemo01
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-culler-role
